version: '3.5'

services:
  imaptodiscord:
    container_name: spielendical
    image: spielendical
    environment:
      - NODE_ENV=development
    volumes:
       - ./db:/spielendical/db
    restart: unless-stopped